# Generated by Django 6.0.7 on 2026-07-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Photo',
            new_name='photo',
        ),
    ]
